# Generated by Django 4.1.7 on 2023-03-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('created_date',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
