# Generated by Django 4.1.7 on 2023-03-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placesOfWork', '0002_alter_placesofwork_options_placesofwork_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placesofwork',
            options={'verbose_name': 'PlaceOfWork', 'verbose_name_plural': 'PlacesOfWork'},
        ),
    ]
