# Generated by Django 4.1.7 on 2023-03-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_options_remove_projects_cat_and_more'),
        ('projectCategories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
