# Generated by Django 4.1.7 on 2023-03-29 10:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workExperience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ('created_date',), 'verbose_name': 'WorkExperience', 'verbose_name_plural': 'WorkExperiences'},
        ),
        migrations.AddField(
            model_name='workexperience',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='period',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='tasks',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
