# Generated by Django 4.1.7 on 2023-03-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workExperience', '0002_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'WorkExperience', 'verbose_name_plural': 'WorkExperiences'},
        ),
    ]
