# Generated by Django 4.1.7 on 2023-05-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workExperience', '0003_alter_workexperience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='place_of_Work_link',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
